### ISSUE TITLE
Why we need gosu?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#10]
Since I don't see gosu used in any of the components we install (bedrock, sage, dokku, etc).

The main theme is to stick as much as possible to the standard installation procedures. If gosu is not mentioned in any installation guide what is the scope of this?

**Comment by elghazal-a** [comment]
gosu is small utility that allows us to run linux command on behalf other users. Since Compose command can't (and shouldn't) be run as root user. I use `gosu` to run compose commands in init.sh as `www-data` user. I hope that answer the question
