### ISSUE TITLE
docker compose up fails

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#12]
Using the latest Docker for windows installed I get the following error

![error01](https://user-images.githubusercontent.com/19224635/36306012-498093c6-1316-11e8-8abc-4d72498edc36.png)

**Comment by elghazal-a** [comment]
I didn't get this error when I run your `setup.bat`, did you pull last changes from git before building?

**Comment by distributev** [comment]
Apparently this was a bug with the latest "stable" release of docker on Windows - I got hints of this on github issues of docker as suggested there I un-installed the stable and installed the "edge" docker and this error when away.

Another option would have been to get an older version of docker which did not have this behavior (for some users upgrading to docker edge version did not help either).

**Comment by elghazal-a** [comment]
This is awkward because I tested with the stable release. Did you test with the stable release by pulling first last changes?

**Comment by distributev** [comment]
docker was giving other errors right after installation when bootstrapping that it could not start / find some linux embedded stuff - I'm 99% it was a docker bug - I'm not sure how it is working on your computer. I did not see other git pushes on the repository after I git clone-it.

In any case now after switching to docker edge that errors are gone - I need to create a user with a password now.

**Comment by elghazal-a** [comment]
I wish I could know what other errors Docker gave you. Anyway, for me, I still have error said `set: illegal option -` that is out of the scope of this issue. If you don't see this error in the edge version it's great, but I'm working to fix it in the stable version.

**Comment by distributev** [comment]
OK it's working now for me it's gone - just focus to get something working in some kind of initial form.
