### ISSUE TITLE
Docker Is asking me for a password but I have no password on Windows

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#13]
My Windows user is password-less but docker is asking for a password which I don't have from where to provide. What do you think is the solution here?

![error02](https://user-images.githubusercontent.com/19224635/36340604-34314238-13e1-11e8-9044-28499c05bda5.png)

**Comment by elghazal-a** [comment]
Yeah I understand. This is Docker limitation. it's fixed by protecting the user with password. Check the issue here https://github.com/docker/for-win/issues/366
