### ISSUE TITLE
How do I know when is started? Where do I see possible errors?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#14]
Please update HowTo.md with information about

* How do I know when is started?
* How long (approximatively) the installation will take the first time?
* How long  (approximatively) will take subsequent executions / restarts?
* Where do I see possible errors?

docker compose up started to execute and for few minutes the prompt was progressing - then the prompt stopped apparently (but was not sure if done or not or if errro) and then after few minutes 1 more new line came on the prompt and then few minutes again nothing was happening and again 1 new line and so on.

* How do I know when everything is started?
* Once done how I can access WordPress / Laravel
* My "work" folder is still empty where are the bedrock / laravel apps installed?
* Where do I see possible errors?

Here is how my prompt looks now.

![q3](https://user-images.githubusercontent.com/19224635/36371838-996fb778-1563-11e8-88f4-0c9d1c51aed1.png)

**Comment by elghazal-a** [comment]
1- The service prints in the logs `'apache2 -D FOREGROUND'` when it's starting. 
You can see full service logs with `docker-compose logs -f wordpress`. If you want to see what services are up and services failed to start, then run `docker-compose ps`. 
I'll update HowTo.md with that though it's more in the scope of Docker/docker-compose

2- I can't say how much time the installation time take, it depends on many factors like internet speed, servers availability... However you can see the progress in the logs

3- subsequent executions / restarts run as fast as running plain docker image. You need just to set `WP_INIT` to other value than yes

4- You can see possible errors in the logs

**Comment by distributev** [comment]
![q4](https://user-images.githubusercontent.com/19224635/36374925-6564f6aa-156d-11e8-922c-d82ac7a4aab2.png)

**Comment by distributev** [comment]
Please update HowTo guide

* When do I know when everything is started? 
* How do I access WordPress, Laravel etc?
* Where exactly / what file path (in which file?) I can find each log file (apache, mysql, etc.)
