### ISSUE TITLE
Work folder still remains empty and in the DOS cmd prompt I get MySQL error

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#16]
Work folder still remains empty and in the DOS cmd prompt I get below error

![e03](https://user-images.githubusercontent.com/19224635/36379533-48b8e4e6-157f-11e8-99ac-29f96a1cb523.png)

**Comment by distributev** [comment]
I have the latest code.

**Comment by elghazal-a** [comment]
This has nothing to do with the project or the code. The error says that already have container called `setup_mysql_1`. In Docker, you can't run 2 different containers with the same name. Please check what actual containers you're running (`docker ps -a`) and clean your unused containers (`docker rm $container_name`)

**Comment by distributev** [comment]
I'll do that - just as a side question this means I cannot reliable start / stop / restart the stuff because I'll get this kind of warnings. Things should be reliable and repeatable.

**Comment by elghazal-a** [comment]
Of course you can start, stop and restart without getting those kind of errors. I don't know what happened to you but maybe you left  stack other terminal and started new stack in new terminal. If you work on the same stack, you wont get that kind of error.

**Comment by distributev** [comment]
Went 1 step further but still ended in error - Now the work folder got populated with some stuff

I still don't know when I will know everything finished. What message should I wait on the screen?

![e04](https://user-images.githubusercontent.com/19224635/36387765-217a846e-159a-11e8-93b3-950a6cc1e24b.png)

**Comment by elghazal-a** [comment]
Great, I think this error is specific to Windows, I'll check that and fix it.
Everything is finished when:
1- You no longer see `waiting for wordpress service to start...` in the logs
and
2- You see `'apache2 -D FOREGROUND'` in the logs

**Comment by distributev** [comment]
"in the logs" - you mean the DOS console logs? or there are log files which I can inspect? I prefer log files on disk in a pre-defined location (all)

To which URL I can access wordpress and laravel? I verified file work/.env file and it has the default values which are coming from BedRock

**Comment by elghazal-a** [comment]
All the logs are printed in the DOS console (your screenshots). Storing logs in file is Docker anti-pattern for many reasons. Besides, Developers will never want to check logs history.
variables in `work/.env` are overwritten in docker-compose yaml file. After successful build/installation, you can access wordpress at `http://127.0.0.1` and laravel at `http://127.0.0.1/lara`.

**Comment by distributev** [comment]
Just managed to view WordPress few seconds before reading your message (by checking DOS console docker containers port mappings information) and /lara after I saw your message. All this information should be in HowTo - a beginner should take Howto and execute steps ==> view the result.

What is the command to shut down everything in 1 command? Now I try to shut down by individually running the kill command for each container. A better way probably exists.

**Comment by elghazal-a** [comment]
Yeah I'll of course improve doc. You can shutdown the whole stack using with CTRL+C.

**Comment by elghazal-a** [comment]
I had the issue you encountered (error (cryptic)). It seems a bug related to windows according to this https://github.com/docker/compose/issues/5019#issuecomment-351495225

I've tested the setup in Powershell and it works fine. Can you please test in Powershell
