### ISSUE TITLE
Failure with the initial setup

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#18]
I just cloned the latest into an empty folder and then executed setup.bat which failed with the following error.

![e05](https://user-images.githubusercontent.com/19224635/36592040-66fcde54-1894-11e8-9be5-c79bd6fe7f55.png)

**Comment by elghazal-a** [comment]
It seems like an issue with docker networking, can you please try to run a basic container like that `docker run --rm -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root  mysql:8.0`

**Comment by distributev** [comment]
It seems it worked

![image](https://user-images.githubusercontent.com/19224635/36597936-fa04b954-18aa-11e8-95a1-ec328df6a8b5.png)

**Comment by elghazal-a** [comment]
This is weird, can you please restart Docker daemon. I also recommend you to run the setup in Powershell

**Comment by distributev** [comment]
I run setup.bat in the same DOS cmd prompt. The command is working and we try to break it? How this will help with the Adminer issue?
