### ISSUE TITLE
htaccess and gitignore configuration files

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#19]
Bedrock comes with both .htaccess and .gitignore files

Laravel the same comes with both  .htaccess and .gitignore files

Double check and make sure for both Bedrock and Laravel we ship the out of the box   .htaccess and .gitignore provided files (so that we don't reinvent the wheel)

**Comment by elghazal-a** [comment]
those .htaccess files are ignored in `.gitignore` which means they are meant to bu used only in dev environment. Do you suggest to remove them from .gitignore?
