### ISSUE TITLE
Refactor and modularize by mirroring the main components

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#22]
The main components we use are Apache, WordPress, BedRock, Sage, Laravel and Adminer ==> the folder structure and the script separation and the script names should reflect the components we use.

Please re-orgnize the scripts and folders like this

![ref](https://user-images.githubusercontent.com/19224635/36732976-8ac74e62-1bcf-11e8-8d74-83ca98d9fea8.png)

![image](https://user-images.githubusercontent.com/19224635/36874819-a67117ee-1dad-11e8-930b-c10ca31d1c2a.png)

You can get inspiration how these projects organize docker images

https://github.com/laradock/laradock has a separate folder / docker file for each component
https://github.com/iron-io/dockers is doing the same

**Comment by elghazal-a** [comment]
I didn't want to comment this issue until we finish #24 discussion and understand well the purpose of each services.

- Please check `docker-compose.yml`, I run Adminer directly from the base image, I don't build custom Adminer Docker image so I don't need Adminer Dockerfile.
- As discussed in #24, there is only one and only one main service which run the apache that serve bedrock, sage and Laravel stuff. 1 service = 1 container = 1 docker image = 1 Dockerfile
There is no way I can split Dockerfile unless you want to run bedrock, sage and laravel in separated container/process/port (which is for sure not what you want)

**Comment by distributev** [comment]
"I don't build custom Adminer Docker image so I don't need Adminer Dockerfile." - OK

"1 service = 1 container = 1 docker image = 1 Dockerfile" - OK now I understand a little bit better we have a single physical container and multiple logical components. In that case is that an option to move the single Dockerfile up one folder and next to the docker-compose.yml and env files but to keep the proposed folder structure to mirror our logical components? And each folder should contain the corresponding shell script sh file with the commands corresponding to the specific component. The numeric folder prefix 00 - 01 - etc. is supposed to keep folders consistently sorted across Windows and Linux. Having everything splitted in smaller scripts helps me better understand.

For instance in wordpress.sh I should easily see the rm command which is removing the stock WP and then in bedrock.sh I should see the command to install composer and then bedrock installation commands, in sage.sh the sage related commands and so on.
