### ISSUE TITLE
WordPress error (locally)

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#23]
![image](https://user-images.githubusercontent.com/19224635/36716845-1fc5fe02-1b9c-11e8-8255-38fb493815a0.png)

**Comment by elghazal-a** [comment]
I remember I had the same error when I was working with mysql version 8.0. I switched back to 5.7 version and I didn't get this error anymore. It seems like mysql client implemented with wordpress is not compatible with 8.0 or need further configuration. What current mysql version did you run? Did you pull last version of this repo?

**Comment by distributev** [comment]
I use whatever version of mysql was configured in the docker file and yes I think I had the latest source code version. We started from the official WordPress docker image provided by Automattic (company behind wordpress) so it's difficult for me to believe Automattic messed it up so bad that they shipped official wordpress docker image with an incompatible mysql version.
