### ISSUE TITLE
Estimated Time required to start everything locally?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#25]
When running locally (setup folder) **_what is a "normal" estimated time_**

1. For the first execution of docker compose up?
2. For subsequent executions (once the images are built)?

I already started the containers few times and I have the impression it takes too much time for everything to start (because the images are built). Maybe I'm not running the correct command and I'm rebuilding containers unnecessary? Yesterday you teached me the command 

docker-compose -p $unique_name up -d --build

What should be the command to run the first time (when the containers should be built) and what would be the command for subsequent executions (when containers should not be built again)?

**Comment by elghazal-a** [comment]
In response to your questions 1 and 2, please check this comment https://github.com/distributev/wordpress-laravel-docker-local-cloud/issues/14#issuecomment-366647799

Regarding your last questions
If you are not familiar with docker-compose, please keep always running `docker-compose -p $unique_name up -d --build`. To improve subsequent executions speed, please set `WP_INIT` to a value other than `yes` until I implement issue #28
