### ISSUE TITLE
Eliminate WP_INIT and PROJECT_PATH from our setup

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#28]
For the PROJECT_PATH you can assume it is ../app

For WP_INIT you can test for the existence of the folder ../app/bedrock and 

- if not found it means it is the first time we run so you execute the full process including the creation of everything required
- if ../app/bedrock folder is found you just start the containers (without recreating anything)

**Comment by elghazal-a** [comment]
I eliminated WP_INIT flag in favor of directories existence check. check this commit eb4b2de8fc054e30d5cb1cae8800c6f8a392693c

Regarging PROJECT_PATH flag, I need you to think twice before eliminating it. In my opinion the project that will be generated should stay outside of this project. Consider `wordpress-laravel-docker-local-cloud` project is like helper project that will generate for you your base project. The project generated should be put in separate folder and versioned in separated git repository.

**Comment by distributev** [comment]
I also thought to the things you said here and did not come (yet) to a clear answer. 

Even with the ../app approach siting next to provisioning and local-compose-up directories (sibling of those 2) the separation is there even if not so drastic like the one you proposed (../app folder is sibling / separated from local-compose-up and provisioning). More specifically I'm thinking to the scenario where I'll have some app PHP code developed (maybe few months old project) which is already provisioned in AWS but for whatever reason I might decide to totally destroy current AWS production environment and provision a totally new one (with more resources or even a new environment on Google Cloud) - In that moment it will be handy to have the provision folder already there waiting for me to use it (2 commands away). I agree even if we do the way you propose we can still "bring" the provision folder back but it will take 1 additional step to fetch it from a different repo and bring it back. One more thing (this is subjective) is that if I have the provision folder as part of the main app repository I'll be more inclined to "take care" and maintain and evolve and further test along with the application (to keep them aligned and in sync). If I'll have it somewhere else and I come to it after 2 years when it might be out of sync with the app I'll just have less care for it (forget about it).

**Comment by distributev** [comment]
Getting everything up on a new computer will involve 1 git clone when everything is in a single repository and 2 git clones when 2 different repos.

I'm just throwing random points...I'm not sure what is the best approach.

**Comment by distributev** [comment]
OK keep PROJECT_PATH as a configuration but it should come with a default value of ../app like this

PROJECT_PATH=../app

 (and app folder should come pre-created with an empty keepme.txt file inside - so that git will version app folder correctly - git has difficulties with empty folders I think). This way I'll have the option to change PROJECT_PATH to a different path if this is what I'll need.
