### ISSUE TITLE
Support for Amazon RDS

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#29]
With the current code what steps are required to do in order to connect to an Amazon RDS database instead of using the current docker my_sql image?

Ideally

- in development (local) the current docker mysql image should be default but it should be possible, if needed, to configure connection to an Amazon RDS instead
- in production (provisioning) it should be the other way around - Amazon RDS should be default but, if needed, it should be possible to configure connection to the current docker mysql image

**Comment by elghazal-a** [comment]
1. In dev env, you can set the connection to other remote mysql by setting variables in `.env` and `DB_HOST` in `docker-compose.yml`
2. In production, RDS is the default db configured. You con configure the connection to any other mysql db. I wrote a script that help to that. You can find in `/home/dokku/connect-to-db.sh`
