### ISSUE TITLE
Understanding the purpose of Sage and Laravel docker services

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#31]
I need to double check something. You said

2- sage: this service watch css/js/ts files and build (compilation, transpile,..) them.
3- laravel: this service watch css/js/ts files and build (compilation, transpile,..) them.

By creating the Sage service do we try to implement ourselves "watch css/js/ts files and build (compilation, transpile,..)"? - We should not do that because

Sage9 has browsersync and WebPack features built-in - this is from their main page https://github.com/roots/sage

- Webpack for compiling assets, optimizing images, and concatenating and minifying files
- Browsersync for synchronized browser testing

which means we shouldn't do anything special ourselves for supporting this feature which should just come for us out of the box (from the fact that we are using Sage9 which has this builtin)

The same is true for Laravel we should not do anything ourselves for "watch css/js/ts files and build (compilation, transpile,..) " because I'm sure Laravel has this feature built-in (though I did not work with Laravel yet but I know that all modern frameworks have this feature built-in and Laravel is a modern framework)

**Comment by elghazal-a** [comment]
I don't implement anything myself, I just run the command provided in the doc.

**Comment by distributev** [comment]
OK - this is how it should be done.
