### ISSUE TITLE
Why we specified ourselves MySQL version?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#32]
How I understand Docker (I might be wrong) if we took a decision to start our image FROM wordpress:4.9.4-php7.2-apache then we'll just use whatever MySQL version is shipped in wordpress:4.9.4-php7.2-apache which means will not have to mess up ourselves with "what version of MySQL we're going to run" and if we'll not mess up ourselves with MySQL version it means the risk of running a wrong version of MySQL will be 0 (because Auttomatic company probably knows what version of WordPress is compatible with what version of MySQL)

![image](https://user-images.githubusercontent.com/19224635/36753593-e271b058-1c06-11e8-8c23-00002d8dee6d.png)

**Comment by elghazal-a** [comment]
`wordpress:4.9.4-php7.2-apache` image doesn't ship mysql with it. It contains php based image configured to run wordpress with apache. Besides, docker containers should contain one and only one service/process. You are free to attach your wordpress with database. Auttomatic should not force you to run specific version of database. You should decide yourself what version you need to run based on criteria (features, security, stability,...). If you don't have any restriction then you should stick with the most stable and well tested version with wordpress. It's up to you to choose the mysql version, this why it's put as parameter in `.env` file

**Comment by distributev** [comment]
OK - you know better - I though wordpress:4.9.4-php7.2-apache is an out of the box image provided by Automattic for their own product WordPress. 

Here https://hub.docker.com/_/wordpress/ it shows an example with MySQL 5.7 like this

Example stack.yml for wordpress:

version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

**Comment by elghazal-a** [comment]
Yeah, I got some issues with mysql 8.0 version (like #23) until I switched to `5.7`.

**Comment by distributev** [comment]
OK maybe I still have v8 and will start to work after I get the latest.
