### ISSUE TITLE
Replace wait.sh with the docker compose depends_on mechanism

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#33]
https://docs.docker.com/compose/startup-order/

**Comment by elghazal-a** [comment]
From that doc "However, Compose does not wait until a container is “ready” (whatever that means for your particular application) - only until it’s running. There’s a good reason for this."
Notice that I'm already using `depends_on`, but it's not enough. Please read that link for more details

**Comment by distributev** [comment]
OK
