### ISSUE TITLE
variables.tf

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#34]
- please re-arrange variables.tf with the required information coming at the top followed by optional keys in descending order based on their importance (however you will define "important")
- and for each optional variable please provide a "smart" default value.

P.S - when organizing your argument is also good so please try to find a good mix between (if possible)

"though I don't prefer organise variable that way. now, they are organized by section, aws variables, dokku variables , wordpress variables,... and if you read description of each variable you'll understand wether it's optionel or not"

**Comment by elghazal-a** [comment]
done
