### ISSUE TITLE
Have EC2 user/password and MySQL login user/password configurable in secret.auto.tfvars.example

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#37]
I believe both EC2 host and MySQL users/passwords should be available for configuration when the environment is provisioned.

**Comment by elghazal-a** [comment]
mysql user can't be configurable because it's hardcoded here https://github.com/dokku/dokku-mysql/blob/master/functions#L72

By the way, there is no need to set mysql user/pass. dokku-mysql create default `mysql` user and set secure password for it
