### ISSUE TITLE
Where is Laravel?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#39]
![where-is-laravel](https://user-images.githubusercontent.com/19224635/36836469-af3fe2c0-1d39-11e8-9b62-c547c36fd7b9.png)

Update 1: Finally Laravel folder came after 12 minutes but the issue remains how can I easily have access and know what is the status with containers and what they are doing (if still working or crashed or whatever)

Update 2: and finally after ~20 minutes I was able to access wordpress using http://localhost:8080 (this URL was failing previously during those 20 minutes before) - I understand the project creation takes time first time but I need feedback during creation / startup / initialization time because if I see all containers UP and then 15 minutes after containers are up Laravel folder is still not there and WP url is not accessible this is confusing.

**Comment by elghazal-a** [comment]
knowing the progress is as easy as following `bedrock_sage_lara` container logs. I'll implement #40 if that could help.

**Comment by distributev** [comment]
#40 for sure will help here. Can you dump the contain logs under a logs folder like this?

![image](https://user-images.githubusercontent.com/19224635/36840337-e3f8b93c-1d44-11e8-8e5b-adb5764d02c2.png)

**Comment by elghazal-a** [comment]
This is not possible, Docker support the following logs driver https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers

I think we had this debate before, I want to tell you again, development logs should not be stored locally, it's something ephemeral and developer will never need to see historic. Besides, storing logs in file can slow down developers when debugging.

**Comment by distributev** [comment]
OK this is fine. 

I remember I raised something similar before but I thought the idea was lost through the cracks of the many things we discussed in parallel.
