### ISSUE TITLE
EVERYTHING IS UP AND RUNNING

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#40]
In the console please show following information when everything is up and running (keep the *** and capitalization EVERYTHING IS UP AND RUNNING so it will STAND UP easily in the console)

![image](https://user-images.githubusercontent.com/19224635/36837645-412db600-1d3d-11e8-997e-431da6f68038.png)

**Comment by distributev** [comment]
Please add also

Adminer app is accessible at this URL - $ADMINER_URL$

**Comment by elghazal-a** [comment]
done
