### ISSUE TITLE
internal files showing under /app folder

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#42]
![image](https://user-images.githubusercontent.com/19224635/36838488-95f55ad8-1d3f-11e8-85f3-62c420af346a.png)

**Comment by elghazal-a** [comment]
.dockerignore, apache-sites, Dockerfile and wordpress.sh are needed for production. They used to build production docker image. They should be in your root project, which is  `/app` in your case

**Comment by distributev** [comment]
Is it possible to handle these files (needed internally for technical reasons but not related with the app business or features) in scripts (and possible in temporarily or internal folder paths which are invisible to app developers) such that the Windows app developers people will not see files like wordpress.sh in the app folder? It is strange to view a file like wordpress.sh on a Windows machine and further more app developers will never be requested to run themselves wordpress.sh or to modify apache-sites.conf

P.S - Yes app developers are expected to have technical knowledge of what is happening under the hood but whatever can be simplified is a good thing.

**Comment by distributev** [comment]
![image](https://user-images.githubusercontent.com/19224635/37275845-90595fb2-25e0-11e8-89c5-4f0c23ebc8ac.png)

**Comment by elghazal-a** [comment]
You are right, `Dockerfile.dev` wont work. Actually, `Dockerfile.dev` and `docker-compose.yml` should not be there, I'll delete them from the generated project. However, `Dockerfile` must be there and can't be hidden. It's used by Dokku to deploy the app.

"To use a dockerfile for deployment, commit a valid Dockerfile to the root of your repository and push the repository to your Dokku installation". More details in  [Dokku doc](http://dokku.viewdocs.io/dokku~v0.11.3/deployment/methods/dockerfiles/).

**Comment by distributev** [comment]
OK - fix and remove whatever needs to be fixed / removed and whatever will remain should be the minimum stuff required to be there and should work fine.
