### ISSUE TITLE
Sage WebPack ports 3000 and 3001

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#50]
I noticed this and I cannot access this URL - Does it need for ports 3000 and 3001 to be forwarded to be accessible?

![image](https://user-images.githubusercontent.com/19224635/36914936-399bf574-1e4f-11e8-85e5-f5d0adec6fb7.png)

**Comment by elghazal-a** [comment]
yes you are right. Those ports need to be forwarded if you want to use browsersync. It's done.
