### ISSUE TITLE
I get EVERYTHING IS UP AND RUNNING but nothing is working

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#54]
Only Adminer Works fine http://localhost:9000

all the other URLs return 

![image](https://user-images.githubusercontent.com/19224635/36970875-4cdab9f0-206a-11e8-8fc8-f4439a8e01a4.png)

![image](https://user-images.githubusercontent.com/19224635/36979354-8143d75e-2087-11e8-8e5a-2771301c2a17.png)

![image](https://user-images.githubusercontent.com/19224635/36981003-3c632a7c-208c-11e8-9e35-3898b376b78f.png)

**Comment by elghazal-a** [comment]
Make sure that `app.dev` is added to your hostfile and mapped with `127.0.0.1`
you can also reach the website via http://127.0.0.1

**Comment by distributev** [comment]
as mentioned in the screen-shot http://127.0.0.1 it's already tried and not working

**Comment by distributev** [comment]
![image](https://user-images.githubusercontent.com/19224635/36972042-fd38e8c8-206d-11e8-952c-cff171f127bd.png)

![image](https://user-images.githubusercontent.com/19224635/36972338-095388b0-206f-11e8-9500-661b843371e7.png)
