### ISSUE TITLE
Could not get main.scss sage git pushes reflected on aws

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#60]
I am adding these changes at the end of main.scss in sage and nothing is happening after I git push
these are the changes

$test-font-stack:    Helvetica, sans-serif;
$test-primary-color: #333;

body {
  font: 100% $test-font-stack;
  background-color: $test-primary-color;
}

**Comment by elghazal-a** [comment]
Have you tried those changes in development environment and you saw the changes?
I tried in my dev environment and I got scss compilation error
```
sage_builder_1       |  WAIT  Compiling...02:43:42
sage_builder_1       | 
sage_builder_1       |  ERROR  Failed to compile with 1 errors02:43:47
sage_builder_1       | 
sage_builder_1       |  error  
sage_builder_1       | 
sage_builder_1       | 
sage_builder_1       | resources/assets/styles/main.scss
sage_builder_1       |  28:1  ✖  Expected no more than 1 empty line   max-empty-lines
sage_builder_1       |  32:1  ✖  Expected indentation of 2 spaces     indentation    
sage_builder_1       |  33:1  ✖  Expected indentation of 2 spaces     indentation
```

You must test your code in dev environment before pushing anything to server.

**Comment by distributev** [comment]
I tried to replicate the compilation error locally and could not because again local changes were not picked. SAGE / yarn / webspack local polling of changes don't work again? Below you can see more details.

![image](https://user-images.githubusercontent.com/19224635/37395935-cfb64632-2777-11e8-9dae-5269e87c3a41.png)

**Comment by elghazal-a** [comment]
make sure you have the manual tweaks in webpack configuration that enables watch polling

**Comment by distributev** [comment]
I always forget to do "manual tweaks"

**Comment by distributev** [comment]
**_I tested again and pushed error free main.scss changes to aws dokku and still I Could not get main.scss sage git pushes reflected on aws._**

Another thing I noticed is in the powershell console where even if it looks like (some) dokku output is available the main.scss compilation errors were not displayed (though at some point I think I noticed a specific error from main.scss in poweshell console but can not remember which one so I can not reproduce) ==> Question - Why some dokku output is available in powershell and some other is not? Is it possible to reliable get all dokku console output displayed on powershell? This would be very useful exactly for this kind of situations.

**Comment by elghazal-a** [comment]
Could you please send me a diff of changes you made? I want to reproduce it locally. 
Regarding your question, what other output that is not available in powershell are you talking about? Dokku doesn't choose or filter logs, it actually prints **ALL** output of commands in Dockerfile
