### ISSUE TITLE
Is local and cloud (aws) deploying different code? Both should deploy exactly the same code (whatever is found in the PROJECT_PATH folder)

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#61]
When deploying to cloud the provision script "re-installs" stock sage and laravel instead of just deploying whatever is found in the app folder? I'm not sure about this it is only a supposition but this might explain #60 also.

I have deployed in parallel local and cloud (aws) and the result is that:

- app.devel local version shows me the modified local version of main.scss (from the app folder)
- app.aws cloud deployment shows the stock sage version of main.scss (at least this is how it looks visually)

![image](https://user-images.githubusercontent.com/19224635/37518218-8a377bdc-2914-11e8-88c5-45860943b1a5.png)

**Comment by elghazal-a** [comment]
of course you deploy the same code. You need to make sure you `git commit` all the changes you have made. type `git status` to see what are changes waiting for you to commit and deploy

**Comment by distributev** [comment]
everything is committed see below (please mind also the folder "app" from where I executed git status and also this is the folder where git init was initiated)

![image](https://user-images.githubusercontent.com/19224635/37519551-c5f0de48-2919-11e8-8289-e38e0367c70a.png)

**Comment by elghazal-a** [comment]
ok please let me reproduce that

**Comment by distributev** [comment]
please analyze / investigate and interpret all this in conjunction with #60 - I think they are related.

**Comment by elghazal-a** [comment]
Okay I investigated the issue and I found that `yarn run build:production` command doesn't generate correctly css files. I replaced it with `yarn run build` in my commit 7f1f72ad until the production command target is fixed. 
You can confirm that it's not working in your local, just run it and see the generated css file if it contains your css changes.

```
docker exec -it  localcomposeup_bedrock_sage_lara_1 bash -c "cd bedrock/web/app/themes/sage/ && yarn run build:production"
```
replace `localcomposeup_bedrock_sage_lara_1` with your `bedrock_sage_lara` container name.
Check the file `sage/dist/styles/mail_xxxxxxx.js`, and see if it does contain your changes. I did that test, and the file doesn't contain my changes
