### ISSUE TITLE
Default database values .env and variables.tf files

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#62]
default database values from .env  differs from default db values from variables.tf ==> if I leave default values I get errors.

Default values in .env and variables.tf should be in sync (just choose yourself default values which makes sense but use the same default values in both configuration files).

**Comment by elghazal-a** [comment]
done

**Comment by distributev** [comment]
In variables.tf 

"mysql_db_name" {
  default = "wordpressDb"

and in .env 

MYSQL_DATABASE=wordpress

which means I rds will be provisioned as wordpressDb but then WP will try to connect to MYSQL_DATABASE=wordpress 

==> troubles

**Comment by elghazal-a** [comment]
okay done
