### ISSUE TITLE
WordPress fails (MySQL issue) when executing the previously working command docker-compose -p $project_name$ up --build

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#63]
![image](https://user-images.githubusercontent.com/19224635/37699854-9e41502a-2ce9-11e8-9632-0ce7e01a92e5.png)

**Comment by elghazal-a** [comment]
Please clean mysql docker volume and retry. The user/password changed in .env but the volume still contain the old user/pass. 
the easiest way to delete the volume is to delete the whole stack
`docker-compose -p $project_name$ down -v`

**Comment by distributev** [comment]
I believe I run this after a prune command docker system prune -a but I'll try what you suggested

**Comment by elghazal-a** [comment]
In fact, prune delete only orphans resources. we want actually to delete volume currently used as well
