### ISSUE TITLE
provisioning/aws terraform apply not working

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#64]
![image](https://user-images.githubusercontent.com/19224635/37708210-0f19449e-2d06-11e8-84ca-0ec63d0cb607.png)

**Comment by elghazal-a** [comment]
please make sure you deployed your app

**Comment by distributev** [comment]
![image](https://user-images.githubusercontent.com/19224635/37709586-f6a42b90-2d0a-11e8-82be-6269d55d3659.png)

**Comment by elghazal-a** [comment]
Please check if you're app is running in the server `docker ps -a`
Check also its logs `docker logs -f app_name`

**Comment by distributev** [comment]
![image](https://user-images.githubusercontent.com/19224635/37802785-1ee93c4a-2e2c-11e8-8763-912b9ead08f5.png)

**Comment by distributev** [comment]
RDS database is up - I just checked.

**Comment by distributev** [comment]
![image](https://user-images.githubusercontent.com/19224635/37823393-a4974a6e-2e89-11e8-905c-6cd9284e5aac.png)

**Comment by elghazal-a** [comment]
Yeah weird, II had the same issue when I used a variable with special chars. I don't know if it's a limitation of terraform or AWS. This is the pattern that works for me `[0-9][a-z][A-Z]-_/`
