### ISSUE TITLE
Database provisioning query

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#65]
Following the aws provisioning scripts it is not clear to me where is the code 

IF default situation (RDS) 
 
do RDS stuff + DON'T DO MySQL docker image stuff

ELSE if MY_SQL docker wanted

DO MySQL docker image stuff + DON'T DO RDS

Please point me to the provisioning code which is doing that part.

**Comment by elghazal-a** [comment]
I added this logic in 4e5425f9a820b3768b886c43026f8cedb1a3a2e7 commit

**Comment by distributev** [comment]
where is the code of connect-to-db.sh?

**Comment by elghazal-a** [comment]
it's in provision.sh. I create connect-to-db.sh from provision.sh. connect-to-db.sh is  helper to let use switch quickly between your dbs
