### ISSUE TITLE
Is Dockerfile vs Dockerfile.DEV still applicable?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#66]
Before I was suggesting to have mirrored env for aws and local and you said they have different purposes ==> we need separate Dockerfile vs Dockerfile.DEV - Accordingly previous days when I was running local compse I was seeing some console output (Step1 of 42) and this output was coming from Dockerfile.DEV - Also Previous days When executing git push dokku master to provision the console output was showing a different Step1 of 15 and most probably this was generated by Dockerfile. The output of the 2 commands was different and was in sync with what you explained (that we need different Dockerfile vs Dockerfile.DEV).

Today for the first time when I executed git push dokku master using the code pushed today I noticed the console was showing the same output as local compose up is showing (Step1 of 42) and it looked strange like the output for provisioning was coming from Dockerfile.DEV

Is this behavior expected? Are Dockerfile vs Dockerfile.DEV still different and is this difference required? If so why the  provisioing git push dokku master shows output generated by Dockerfile.DEV?

![image](https://user-images.githubusercontent.com/19224635/37770985-7050d256-2dd6-11e8-984f-5688bc5f4565.png)

**Comment by elghazal-a** [comment]
yes Dockerfile and Dockerfile.dev are different and each one is intended to run in each environment. I see in the screenshot that those steps are coming from Dockerfile. Which is expected.

**Comment by distributev** [comment]
Can you please double check the expected scripts are executed for each situation? Are you sure this is the output of Dockerfile?

What I am saying is that I'm 90% these steps are from Dockerfile.DEV and not from Dockerfile - I executed many times the scripts and I came to know which is outputting what. Today I was provisioning and was looking to the screen - why I see output much different than yesterday? - and why this output is the one I used to see when doing docker compose up locally? As I said I'm not 100% you know better and if you'll double check than it will be good enough for me. 

Coming back to my main difficulty is that aws + rds still returns a blue error screen and I cannot test. I though the code you pushed today was expected to fix that problem.

**Comment by elghazal-a** [comment]
I already double checked. The output you highlighted in the screenshot come from Dockerfile https://github.com/distributev/wordpress-laravel-docker-local-cloud/blob/master/local-compose-up/Dockerfile#L77

Dokku picks automatically Dockerfile, it's insane that it uses Dockerfile.dev
