### ISSUE TITLE
Is wp-cli needed?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#9]
I see Bedrock does not need wp-cli to install word press - why would we fetch it?

Bedrock downloads word press like any other php dependency and then Bedrock handles the installation of WordPress.

What was the need for us to use wp-cli because bedrock already handles installation for us?

**Comment by elghazal-a** [comment]
you are right wp-cli is not need by Bedrock since wordpress is fetched by Composer as dependency. I use wp-cli in init.sh script to initialize wordpress. Unless you want to initialize wordpress manually through the user interface, wp-cli is needed to automate the initialization

**Comment by distributev** [comment]
In that case I need wp-cli (I don't want to install WordPress manually) 

If I just do the standard Bedrock installation and I browse to /wp-admin URL what do I get?

**Comment by elghazal-a** [comment]
You get wp-admin interface in order to set user, password...

**Comment by distributev** [comment]
OK
